root = "" # absolute path of the data directory on this computer

data_nasdl          = "{Data}_NASDL"
data_processed      = "{Data}_Processed"
dataset_cropped     = "{Dataset}_Cropped" # (previous ver.) AP with HHC (Horiz half cut)
dataset_cropped_v2  = "{Dataset}_Cropped_v2" # (previous ver.) AP with HHC (Horiz half cut)
dataset_cropped_v3  = "{Dataset}_DL"
dataset_ml          = "{Dataset}_ML"
model_bfseg         = "{Model}_BFSeg"
model_cellpose      = "{Model}_Cellpose"
model_history       = "{Model}_DL"
model_prediction    = "{Results}_DL"
result_ml           = "{Results}_ML"
result_adv          = "{Results}_Advanced"

fiji_local = "" # absolute path of "Fiji (ImageJ)" on this computer