from .baseimagetester import BaseImageTester
from .basesurfdgtimagetester import BaseSurfDGTImageTester

from .vitb16imagetester import VitB16ImageTester
from .vitb16aonlyimagetester import VitB16AOnlyImageTester
from .vitb16ponlyimagetester import VitB16POnlyImageTester

from .vitb16nocropimagetester import VitB16NoCropImageTester
from .vitb16aonlynocropimagetester import VitB16AOnlyNoCropImageTester
from .vitb16ponlynocropimagetester import VitB16POnlyNoCropImageTester

from .vitb16surfdgtimagetester import VitB16SurfDGTImageTester
from .vitb16aonlysurfdgtimagetester import VitB16AOnlySurfDGTImageTester
from .vitb16ponlysurfdgtimagetester import VitB16POnlySurfDGTImageTester

from .resnet50imagetester import ResNet50ImageTester

from .resnet50nocropimagetester import ResNet50NoCropImageTester
