[data_processed]
  instance_desc = "20240219_fixmm3d" # dir_name = {`instance_desc`}_Academia_Sinica_i[num]
  palmskin_result_name = "03_RGB_direct_max_zproj.tif"
  cluster_desc = "SURF3C_KMeansORIG_RND2022"
  # clustered file: Clustered_File/`cluster_desc`/{`cluster_desc`}_datasplit.csv'

# -----------------------------------------------------------------------------\
[seg_results]
  seg_desc = "Cellpose" # 'SLIC' or 'Cellpose'
  base_size = "W512_H1024"

# -----------------------------------------------------------------------------\
[SLIC]
  n_segments = 200
  dark = 40
  merge = 10
  debug_mode = false
  # `dark` and `merge` are two parameters as color space distance, \
  #   determined by experiences

# params from 'Academia_Sinica'
#  palmskin_result_alias = "RGB_direct_max_zproj"
#  n_segments = 500
#  dark = 40
#  merge = 12

# other param set
#  palmskin_result_alias = "RGB_m3d_HE"
#  n_segments = 500
#  dark = 40
#  merge = 12

# -----------------------------------------------------------------------------\
[Cellpose]
  cp_model_name = "cp_231_palmskin" # `model_file` under "{Model}_Cellpose/"
  channels = [0, 0]
  merge = 10
  debug_mode = false

# -----------------------------------------------------------------------------\
[ML]
  max_topn_patch = 30
  single_feature = "cell_coverage"
  img_mode = "RGB" # RGB / GRAY
  img_resize = [224, 224] # [width, height]