[instance_desc]
  old = "20231229_manualroi" # dir_name = {`instance_desc`}_Academia_Sinica_i[num]
  new = "" # dir_name = {`instance_desc`}_Academia_Sinica_i[num]

# -----------------------------------------------------------------------------\
[copy_info]
  image_type = "brightfield" # 'palmskin' or 'brightfield'
  result_name = [
    "Manual_measured_mask.tif",
    "ManualAnalysis.csv",
    "Manual_cropped_BF--MIX.tif",
    "UNet_predict_mask.tif",
    "UNetAnalysis.csv",
    "UNet_cropped_BF--MIX.tif"
  ]
  # Note: if `result_name` is a directory,
  #         will copy a directory tree.