[data_processed]
  instance_desc = "20230904_update" # dir_name = {`instance_desc`}_Academia_Sinica_i[num]

# -----------------------------------------------------------------------------\
[collection]
  image_type = "brightfield" # 'palmskin' or 'brightfield'
  result_name = "UNet_cropped_BF--MIX.tif"
  log_mode = "missing" # 'missing' or 'finding' (different representation in log file)