[data_processed]
  instance_desc = "20230904_update" # dir_name = {`instance_desc`}_Academia_Sinica_i[num]
  palmskin_result_alias = "RGB_HE_fusion"
  cluster_desc = "SURF3C_KMeansORIG_RND2022"
  # palmskin_result_alias: a key in '{`palmskin_reminder`}_PalmSkin_preprocess/palmskin_result_alias_map.toml'
  # clustered file: Clustered_xlsx/`cluster_desc`/{`cluster_desc`}_data.xlsx'

# -----------------------------------------------------------------------------\
[param]
  random_seed  = 2022 # choosing upper or lower part as train. (half cut of the original image)
  crop_size    = 256  # [256, 512], size to crop the image.
  shift_region = "1/4"    # offset (overlapping region) between the cropped images,
                          # e.g. `shift_region` = 1/3, the overlapping region for each cropped image is 2/3.
  intensity    = 30   # threshold to define pixels is too dark or not.
  drop_ratio   = 0.45     # threshold to decide the cropped image 'preserve' or 'discard',
                          # e.g. if (too_dark_pixels / all_pixels) > `drop_ratio`, discard the cropped image.
  dynamic_select = false  # crop and filter the images dynamically during training (training_set only)
