note = "[v4.3] loss=CE+MSE, Dropout2d off, inner `Sequential` p=0.3, aug -> drop_too_dark -> regx(set_[.*]px_to_[.*])"

# -----------------------------------------------------------------------------\
[dataset]
  seed_dir = "RND2022"
  data = "{20240219_fixmm3d}_Academia_Sinica_i722"
  palmskin_result = "03_RGB_direct_max_zproj"
  base_size = "W512_H1024"
  classif_strategy = "KMeansORIG"
  file_name = "DS_SURF3C_CRPS256_SF14_INT30_DRP65.csv"

# -----------------------------------------------------------------------------\
[model]
  name = "vit_b_16"
  pretrain = "IMAGENET1K_V1"
  # model options: vit_b_16, resnet50

# -----------------------------------------------------------------------------\
[train_opts]
  epochs = 500
  batch_size = 64

[train_opts.cpu]
  num_workers = 4 # Linux only
  # Warning: if `num_workers` != 0, may not use `debugpy` correctly in 'vscode jupyter extension'

[train_opts.cuda]
  index = 0
  use_amp = true # Automatic Mixed Precision

[train_opts.debug_mode]
  enable = false # if `true`, sample `rand_select` images only
  rand_select = 100 # samples for debugging

[train_opts.data]
  use_hsv = false # using 'HSV' color models when getting item from the Dataset
  forcing_balance = false # if `false` will apply `class_weight` to Loss function
  forcing_sample_amount = 2800 # (NotImplemented) set constant number of images for each class
  random_crop = true # `train_set` only, if `false` will use pre-crop `train_set` image
  add_bg_class = false # (Deprecated) preserve the `discard` images but replace its class to "BG" (background)
  aug_on_fly = true # `train_set` only, do augmentation when getting image from the Dataset immediately
  # Notification:
  # - `forcing_sample_amount` isn't Implemented, do NOT set `forcing_balance` to true
  # - Can't set `random_crop` = true if `add_bg_class` = false, cause random crop may generate a discard image
  # - Pre-augmentation action is removed from workflow, do NOT set `aug_on_fly` to false

[train_opts.optimizer]
  learning_rate = 1e-5
  weight_decay = 0.01

[train_opts.lr_schedular]
  enable = false
  step = 20
  gamma = 0.1

[train_opts.earlystop]
  enable = true
  max_no_improved = 50