[model_prediction]
  time_stamp = "20231014_05_23_57_"
  state = "best" # 'best' or 'final' (model.pth)

# -----------------------------------------------------------------------------\
[test_opts]
  batch_size = 512

[test_opts.debug_mode]
  enable = false # if `true`, sample `rand_select` images only
  rand_select = 100 # samples for debugging

[test_opts.cuda]
  index = 0