[model_prediction]
  time_stamp = "20240117_15_35_42_"
  state = "best" # 'best' or 'final' (model.pth)

# -----------------------------------------------------------------------------\
[test_opts]
  batch_size = 64

[test_opts.cuda]
  index = 0

[test_opts.debug_mode]
  enable = false # if `true`, sample `rand_select` images only
  rand_select = 100 # samples for debugging

# -----------------------------------------------------------------------------\
[cam]
  enable = true
  colormap = "COLORMAP_JET"
  # - options of colormap:
  #   ref: https://docs.opencv.org/4.6.0/d3/d50/group__imgproc__colormap.html#ga9a805d8262bcbe273f16be9ea2055a65